# version: '3.8'

services:

  mongo:
    image: mongo:latest  
    container_name: mongo-db  
    ports:
      - 27017:27017 
    restart: always 
    environment:
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}

  mongo-express:
    image: mongo-express:latest 
    container_name: mongo-client  
    restart: always  
    ports:
     - 4040:4040
    environment:
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}